services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    volumes:
      - /Users/gyeongjae/Desktop/.db/mongodb/data:/data/db
      - /Users/gyeongjae/Desktop/.db/mongodb/config:/etc/db
