version: '3.8'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: luca
      POSTGRES_PASSWORD: slfl4861
    stdin_open: true
    tty: true
    ports:
      - 5432:5432
    volumes:
      - /Users/luca/Desktop/infra/db/postgres/data:/var/lib/postgresql/data

